### ISSUE TITLE
Screenshot 

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [Zohrab039/HowTo#1]
Etdiyin şeylərin skrinşotunu çəkib README'yə qoysan əla olar. :)

**Comment by Zohrab039** [comment]
Onu necə edəcəyimi bilmədiyimə görə edə bilmirəm təəssüfki😕

**Comment by isbendiyarovanezrin** [comment]
"[Lightshot](https://app.prntscr.com)" ilə çəkə bilərsən.

**Comment by isbendiyarovanezrin** [comment]
README'yə yerləşdirmək də asandır. [Bu](https://www.w3schools.io/file/github-readme-image) qaynağa göz ata bilərsən.

**Comment by Zohrab039** [comment]
Təşəkkürlər
